{{- if .Values.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: {{ include "openim-rpc-auth.fullname" . }}
spec:
  endpoints:
    - interval: 15s
      port: metrics-port
  selector:
    {{- include "openim-rpc-auth.selectorLabels" . | nindent 4 }}
{{- end }}