image:
  repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/admin-api
  pullPolicy: Always
  tag: "dev"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: openim1.nsddd.top
      paths:
        - path: /complete_admin(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: webapitls  #your hostname tls
      hosts:
        - openim1.nsddd.top
chat-api:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/chat-api
    pullPolicy: Always
    tag: "dev"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: openim1.nsddd.top
        paths:
          - path: /chat(/|$)(.*)
            pathType: ImplementationSpecific
    tls:
      - secretName: webapitls  #your hostname tls
        hosts:
          - openim1.nsddd.top


admin-rpc:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/admin-rpc
    pullPolicy: Always
    tag: "dev"
chat-rpc:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/chat-rpc
    pullPolicy: Always
    tag: "dev"




config:
  envs:
    discovery: k8s
  zookeeper:
    schema: openim
    zkAddr:
      - 127.0.0.1:12181
    username: ""
    password: ""

  chatApi:
    openImChatApiPort: [ 80 ]
    listenIP:

  adminApi:
    openImAdminApiPort: [ 80 ]
    listenIP:

  rpc:
    registerIP:                            #作为rpc启动时，注册到zookeeper的IP，api/gateway能访问到此ip和对应的rpcPort中的端口
    listenIP:                               #默认为0.0.0.0

  rpcPort:
    openImAdminPort: [ 80 ]
    openImChatPort: [ 80 ]
  rpcRegisterName:
    openImAdminName: openimchat-admin-rpc:80
    openImChatName: openimchat-chat-rpc:80

  # 没有配置表示和OpenIM一致
  mysql:
    address: [ im-mysql:3306 ]            #目前仅支持单机
    username: root                          #用户名
    password: openIM123                     #密码
    #database: openIM_v2                     #不建议修改
    maxOpenConn: 1000                       #最大连接数
    maxIdleConn: 100                        #最大空闲连接数
    maxLifeTime: 60                         #连接可以重复使用的最长时间（秒）
    logLevel: 4                             #日志级别 1=slient 2=error 3=warn 4=info
    slowThreshold: 500                      #慢语句阈值 （毫秒）
    database: openim_enterprise

  # 没有配置表示和OpenIM一致
  log:
    storageLocation: ../logs/           #存放目录
    rotationTime: 24                    #日志旋转时间
    remainRotationCount: 2              #日志数量
    remainLogLevel: 6                   #日志级别 6表示全都打印，
    isStdout: true
    isJson: false
    withStack: false

  secret: openIM123
  tokenPolicy:
    expire: 86400

  verifyCode:
    validTime: 300 # 验证码有效时间
    validCount: 5 # 验证码有效次数
    uintTime: 86400 # 单位时间间隔
    maxCount: 10 # 单位时间内最大获取次数
    superCode: "666666" # 超级验证码(只有use为空时使用)
    len: 6 # 验证码长度
    use: "" # 使用的验证码服务(use: "ali")
    ali:
      endpoint: "dysmsapi.aliyuncs.com"
      accessKeyId: ""
      accessKeySecret: ""
      signName: ""
      verificationCodeTemplateCode: ""

  # 获取ip的header,没有配置直接获取远程地址
  #proxyHeader: "X-Forwarded-For"

  adminList:
    - adminID: admin1
      nickname: chat1
      imAdmin: openIM123456
    - adminID: admin2
      nickname: chat2
      imAdmin: openIM654321
    - adminID: admin3
      nickname: chat3
      imAdmin: openIMAdmin


  openIMUrl: "http://openimserver-openim-api"

  redis:
    address: [ im-redis-master:6379 ]
    username: ''
    password: openIM123
