image:
  repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/admin-api
  pullPolicy: Always
  tag: "dev"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: openim1.nsddd.top
      paths:
        - path: /complete_admin(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: webapitls  #your hostname tls
      hosts:
        - openim1.nsddd.top
chat-api:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/chat-api
    pullPolicy: Always
    tag: "dev"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: openim1.nsddd.top
        paths:
          - path: /chat(/|$)(.*)
            pathType: ImplementationSpecific
    tls:
      - secretName: webapitls  #your hostname tls
        hosts:
          - openim1.nsddd.top


admin-rpc:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/admin-rpc
    pullPolicy: Always
    tag: "dev"
chat-rpc:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/chat-rpc
    pullPolicy: Always
    tag: "dev"





