
image:
  repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-api
  pullPolicy: Always
  tag: "dev"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: openim1.nsddd.top # your hostname
      paths:
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: webapitls  #your hostname tls
      hosts:
        - openim1.nsddd.top
openim-msggateway:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-msggateway
    tag: "dev"
    pullPolicy: Always
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: openim1.nsddd.top # your hostname
        paths:
          - path: /msg_gateway(/|$)(.*)
            pathType: ImplementationSpecific
    tls:
      - secretName: webapitls  #your hostname tls
        hosts:
          - openim1.nsddd.top
openim-msgtransfer:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-msgtransfer
    tag: "dev"
    pullPolicy: Always
openim-push:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-push
    tag: "dev"
    pullPolicy: Always
openim-rpc-auth:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-rpc-auth
    tag: "dev"
    pullPolicy: Always
openim-rpc-conversation:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-rpc-conversation
    tag: "dev"
    pullPolicy: Always
openim-rpc-friend:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-rpc-friend
    tag: "dev"
    pullPolicy: Always
openim-rpc-group:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-rpc-group
    tag: "dev"
    pullPolicy: Always
openim-rpc-msg:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-rpc-msg
    tag: "dev"
    pullPolicy: Always
openim-rpc-third:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-rpc-third
    tag: "dev"
    pullPolicy: Always
openim-rpc-user:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-rpc-user
    tag: "dev"
    pullPolicy: Always

