image:
  repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/openim-web
  pullPolicy: Always
  tag: "dev"


ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: openim1.nsddd.top #your hostname
      paths:
        - path: /openim-front(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: webapitls #your hostname tls
      hosts:
        - openim1.nsddd.top