global:
  storageClass: "nfs-client"
controller:
  replicaCount: 3
sasl:
  client:
    users:
      - root
    passwords: "proot"


provisioning:
  enabled: true
  numPartitions: 1
  replicationFactor: 1
  topics:
    - name: latestMsgToRedis
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
    - name: msgToPush
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1
    - name: offlineMsgToMongoMysql
      partitions: 1
      replicationFactor: 1
      config:
        max.message.bytes: 64000
        flush.messages: 1