global:
  storageClass: "nfs-client"
mode: standalone
auth:
  rootUser: root
  rootPassword: "openIM123"
defaultBuckets: "openim"
persistence:
  size: 1Gi

ingress:
  enabled: false
  ingressClassName: "nginx"
  hostname: openim2.nsddd.top #hostname for minioconsole
  path: /
  servicePort: minio-console
  extraTls:
    - hosts:
        - openim2.nsddd.top
      secretName: openim2tls

apiIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: openim1.nsddd.top #hostname for minioapi
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /im-minio-api(/|$)(.*)
  pathType: ImplementationSpecific
  servicePort: minio-api
  extraTls:
    - hosts:
        - openim1.nsddd.top
      secretName: webapitls