#This configuration file is used to override the use of the value. yaml variable. You can modify it according to your own needs.
#If you modify the account information inside, it may need to be synchronized in the application file
global:
  # this is your storageClass,Please change in according to the k8s environment settings of your server
  storageClass: "nfs-client"
  redis:
    password: "openIM123"

master:
  persistence:
    size: 1Gi
replica:
  replicaCount: 1
  persistence:
    size: 1Gi