controller:
  name: controller
  image:
    registry: m.daocloud.io
    image: registry.k8s.io/ingress-nginx/controller
  hostNetwork: true
  service:
    enabled: true
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
      tcp:
        8080: 32808
  admissionWebhooks:
    patch:
      enabled: true
      image:
        registry: m.daocloud.io
        image: registry.k8s.io/ingress-nginx/kube-webhook-certgen

defaultBackend:
  enabled: false
  name: defaultbackend
  image:
    registry: m.daocloud.io
    image: registry.k8s.io/defaultbackend-amd64